# Generated by Django 4.1.2 on 2023-09-15 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classification', '0003_remove_project_exportpath'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='labelType',
            field=models.SmallIntegerField(choices=[(1, 'Video')], default=1, verbose_name='Label Type'),
        ),
    ]
