# Generated by Django 3.2.6 on 2022-10-06 07:17

from django.db import migrations, models
import django.db.models.deletion
import image.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('project', '0003_remove_project_exportpath'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.FileField(max_length=128, upload_to=image.models.user_directory_path)),
                ('image_info', models.JSONField(default={}, null=True)),
                ('data', models.JSONField(default={}, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.project')),
            ],
        ),
    ]
