# Generated by Django 4.1.2 on 2022-10-31 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='data',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='image_info',
            field=models.JSONField(null=True),
        ),
    ]
