# Generated by Django 3.2.6 on 2022-09-09 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projecName', models.CharField(max_length=30, verbose_name='Project name')),
                ('labelType', models.SmallIntegerField(choices=[(1, 'Video'), (2, 'Image')], verbose_name='Label Type')),
            ],
        ),
    ]
