# Generated by Django 3.2.6 on 2022-09-30 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_project_exportpath'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='exportPath',
        ),
    ]
