# Generated by Django 3.2.6 on 2022-09-11 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0002_auto_20220910_0342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='data',
            field=models.JSONField(default={}),
        ),
    ]
